name: Run Server Renewal Script

on:
  schedule:
    - cron: '0 0 * * *'     # 00:00 UTC
    - cron: '48 4 * * *'    # 04:48 UTC
    - cron: '36 9 * * *'    # 09:36 UTC
    - cron: '24 14 * * *'   # 14:24 UTC
    - cron: '12 19 * * *'   # 19:12 UTC
  workflow_dispatch:        # Manual trigger support

jobs:
  renew_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run server renewal script
        env:
          XSRF_TOKEN: ${{ secrets.XSRF_TOKEN }}
          SESSION_COOKIE: ${{ secrets.SESSION_COOKIE }}
        run: python renew.py
