name: Run Server Renewal Script

on:
  schedule:
    - cron: '0 0 * * *'    # 00:00 UTC
    - cron: '0 5 * * *'    # 05:00 UTC
    - cron: '0 10 * * *'   # 10:00 UTC
    - cron: '0 15 * * *'   # 15:00 UTC
    - cron: '0 20 * * *'   # 20:00 UTC
  workflow_dispatch:       # Manual trigger support

jobs:
  renew_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run server renewal script
        env:
          XSRF_TOKEN: ${{ secrets.XSRF_TOKEN }}
          SESSION_COOKIE: ${{ secrets.SESSION_COOKIE }}
        run: python renew.py
